"""Render an architecture's diagram (nodes/edges) to a PNG for Slack.

The backend returns the same diagram data the web canvas draws
(architecture.diagram.nodes / .edges, with x/y/width/height per node). This
script lays it out as SVG in headless Chromium and screenshots it, so the
Slack review thread can show the picture, like the website does.

Usage: python slack/render_diagram.py <architecture.json> <out.png>
Prints the output path on success; exits 2 if there is no diagram data.
"""

import html
import json
import sys

TYPE_COLORS = {
    "compute": "#4299e1", "database": "#9f7aea", "storage": "#48bb78",
    "network": "#ed8936", "security": "#f56565", "serverless": "#38b2ac",
    "analytics": "#ecc94b", "ml": "#ed64a6", "container": "#667eea",
}
BG, CARD, TEXT, SUB, COST = "#151718", "#22262b", "#e8eaed", "#9aa0a6", "#7ee787"


def esc(s):
    return html.escape(str(s or ""))


def main(arch_path: str, out_path: str) -> int:
    arch = json.load(open(arch_path))
    d = arch.get("diagram") or {}
    nodes = d.get("nodes") or []
    edges = d.get("edges") or []
    if not nodes:
        print("NO_DIAGRAM", file=sys.stderr)
        return 2

    # Fit the diagram's coordinate space into the canvas.
    min_x = min(n.get("x", 0) for n in nodes)
    min_y = min(n.get("y", 0) for n in nodes)
    max_x = max(n.get("x", 0) + n.get("width", 160) for n in nodes)
    max_y = max(n.get("y", 0) + n.get("height", 80) for n in nodes)
    span_x, span_y = max(max_x - min_x, 1), max(max_y - min_y, 1)
    W, H, PAD, TOP = 1400, 860, 60, 90
    sx = (W - 2 * PAD) / span_x
    sy = (H - TOP - 2 * PAD) / span_y
    s = min(sx, sy, 1.6)

    def tx(n):
        return PAD + (n.get("x", 0) - min_x) * s

    def ty(n):
        return TOP + PAD + (n.get("y", 0) - min_y) * s

    by_id = {n.get("id"): n for n in nodes}
    parts = []

    # Edges first (under the nodes), with arrowheads and optional labels.
    parts.append(
        '<defs><marker id="arr" viewBox="0 0 10 10" refX="9" refY="5" '
        'markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
        f'<path d="M 0 0 L 10 5 L 0 10 z" fill="{SUB}"/></marker></defs>'
    )
    for e in edges:
        a, b = by_id.get(e.get("from")), by_id.get(e.get("to"))
        if not a or not b:
            continue
        ax = tx(a) + a.get("width", 160) * s / 2
        ay = ty(a) + a.get("height", 80) * s / 2
        bx = tx(b) + b.get("width", 160) * s / 2
        by = ty(b) + b.get("height", 80) * s / 2
        parts.append(
            f'<line x1="{ax:.0f}" y1="{ay:.0f}" x2="{bx:.0f}" y2="{by:.0f}" '
            f'stroke="{SUB}" stroke-width="2" stroke-opacity="0.65" marker-end="url(#arr)"/>'
        )
        if e.get("label") or e.get("type"):
            mx, my = (ax + bx) / 2, (ay + by) / 2
            parts.append(
                f'<text x="{mx:.0f}" y="{my - 6:.0f}" fill="{SUB}" font-size="11" '
                f'text-anchor="middle">{esc(e.get("label") or e.get("type"))}</text>'
            )

    for n in nodes:
        x, y = tx(n), ty(n)
        label = str(n.get("label") or n.get("id") or "")[:30].rstrip(" (-,")
        sub = str(n.get("subLabel") or n.get("type") or "")[:36].rstrip(" (-,")
        # Node must be wide enough for its text (the source width often isn't).
        w = max(n.get("width", 160) * s, 150, 30 + len(label) * 9.2, 30 + len(sub) * 6.6)
        h = max(n.get("height", 80) * s, 74)
        color = TYPE_COLORS.get((n.get("type") or "").lower(), "#4299e1")
        icon = n.get("icon") if isinstance(n.get("icon"), str) and len(n.get("icon", "")) <= 3 else ""
        cost = n.get("cost")
        cost_txt = f"${cost:g}/mo" if isinstance(cost, (int, float)) and cost else ""
        parts.append(
            f'<g><rect x="{x:.0f}" y="{y:.0f}" width="{w:.0f}" height="{h:.0f}" rx="12" '
            f'fill="{CARD}" stroke="{color}" stroke-width="2.5"/>'
            f'<text x="{x + 14:.0f}" y="{y + 26:.0f}" fill="{TEXT}" font-size="15" font-weight="700">'
            f'{esc(icon)} {esc(label)}</text>'
            f'<text x="{x + 14:.0f}" y="{y + 45:.0f}" fill="{SUB}" font-size="12">{esc(sub)}</text>'
            + (f'<text x="{x + 14:.0f}" y="{y + h - 10:.0f}" fill="{COST}" font-size="12" '
               f'font-weight="600">{cost_txt}</text>' if cost_txt else "")
            + "</g>"
        )

    name = esc(arch.get("name") or "Architecture")
    provider = esc((arch.get("provider") or "").upper())
    total = arch.get("metadata", {}).get("totalCost")
    total_txt = f' · est. ${total}/mo' if total else ""
    header = (
        f'<text x="{PAD}" y="46" fill="{TEXT}" font-size="24" font-weight="800">🏗️ {name}</text>'
        f'<text x="{PAD}" y="70" fill="{SUB}" font-size="14">{provider}{total_txt} · '
        f'{len(nodes)} components · generated by Nemotron on self-hosted vLLM</text>'
    )

    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" '
        f'style="background:{BG};font-family:-apple-system,Segoe UI,Arial">'
        f'<rect width="{W}" height="{H}" fill="{BG}"/>' + header + "".join(parts) + "</svg>"
    )

    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page(viewport={"width": W, "height": H})
        page.set_content(f'<body style="margin:0">{svg}</body>')
        page.wait_for_timeout(250)
        page.screenshot(path=out_path)
        browser.close()
    print(out_path)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1], sys.argv[2]))
